;
; File generated by cc65 v 2.18 - Git f75657d
;
	.fopt		compiler,"cc65 v 2.18 - Git f75657d"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_level_number
	.export		_game_phase
	.export		_game_progress
	.export		_map
	.export		_you_move_direction
	.export		_preproc_helper
	.export		_helpers
	.export		_last_obj_index
	.export		_last_text_index
	.export		_objects
	.export		_obj_prop
	.export		_obj_has
	.export		_obj_is_word
	.export		_rule_exists

.segment	"BANKDATA"

_you_move_direction:
	.byte	$04
.segment	"DATA"
_objects:
	.res	700,$00
.segment	"BANKDATA"

.segment	"BANKDATA"

.segment	"BANKDATA"
_level_number:
	.res	1,$00
_game_phase:
	.res	1,$00
_game_progress:
	.res	14,$00
_map:
	.res	240,$00
_preproc_helper:
	.res	64,$00
_helpers:
	.res	8,$00
_last_obj_index:
	.res	1,$00
_last_text_index:
	.res	1,$00
_obj_prop:
	.res	256,$00
_obj_has:
	.res	32,$00
_obj_is_word:
	.res	16,$00
_rule_exists:
	.res	16,$00

