;
; File generated by cc65 v 2.18 - Git f75657d
;
	.fopt		compiler,"cc65 v 2.18 - Git f75657d"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_memset
	.import		_audio_sfx
	.export		_handle_interactions
	.importzp	_local_x
	.importzp	_local_y
	.importzp	_local_index
	.importzp	_local_type
	.importzp	_local_text_type
	.importzp	_local_flags
	.importzp	_local_temp1
	.importzp	_local_temp2
	.importzp	_map_index
	.importzp	_lookup_index
	.importzp	_array_index
	.importzp	_array_value
	.import		_game_phase
	.import		_objects
	.import		_obj_prop
	.import		_obj_has
	.import		_obj_is_word
	.import		_rule_exists
	.import		_map
	.import		_helpers
	.import		_last_obj_index
	.import		_last_text_index
	.import		_map_lookup
	.import		_obj_prop_lookup
	.import		_one_lshift_lookup
	.export		_create_direction
	.export		_create_object
	.export		_teleport
	.export		_create_bang
	.export		_kill
	.export		_process_teleports
	.export		_preprocess_interactions

.segment	"BANKDATA"

.segment	"BANKDATA"
_create_direction:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ handle_interactions (void)
; ---------------------------------------------------------------

.segment	"BANKCODE"

.proc	_handle_interactions: near

.segment	"BANKCODE"

;
; preprocess_interactions();
;
	jsr     _preprocess_interactions
;
; for (local_index = 0; local_index < last_obj_index; ++local_index)
;
	lda     #$00
	sta     _local_index
	tax
L0323:	lda     _local_index
	cmp     _last_obj_index
	txa
	sbc     #$00
	jcs     L0260
;
; if (IS_KILLED(local_index) || IS_CREATED(local_index))
;
	ldy     _local_index
	lda     _objects+560,y
	and     #$08
	jne     L0344
	ldy     _local_index
	lda     _objects+560,y
	and     #$20
	jne     L0344
;
; local_type = objects.type[local_index];
;
	ldy     _local_index
	lda     _objects+280,y
	sta     _local_type
;
; local_x = objects.x[local_index];
;
	ldy     _local_index
	lda     _objects,y
	sta     _local_x
;
; local_y = objects.y[local_index];
;
	ldy     _local_index
	lda     _objects+140,y
	sta     _local_y
;
; MapGet(local_x, local_y, local_flags);
;
	ldy     _local_y
	lda     _map_lookup,y
	clc
	adc     _local_x
	sta     _array_index
	ldy     _array_index
	lda     _map,y
	sta     _local_flags
;
; if (local_flags == INTERACT_NONE)
;
	lda     _local_flags
;
; continue;
;
	jeq     L0344
;
; lookup_index = obj_prop_lookup[local_type];
;
	ldy     _local_type
	lda     _obj_prop_lookup,y
	sta     _lookup_index
;
; if ((local_flags & INTERACT_YOU))
;
	lda     _local_flags
	and     #$01
	beq     L0329
;
; ObjPropGetByIndex(lookup_index, PROP_WIN, array_value);
;
	lda     _lookup_index
	clc
	adc     #$01
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if ( (helpers.pick_exists_as_object==false) && array_value)
;
	lda     _helpers
	bne     L0327
	lda     _array_value
	beq     L0327
;
; game_phase = LEVEL_WON;
;
	lda     #$02
	sta     _game_phase
;
; break;
;
	jmp     L0260
;
; ObjPropGetByIndex(lookup_index, PROP_PICK, array_value);
;
L0327:	lda     _lookup_index
	clc
	adc     #$07
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if (array_value)
;
	lda     _array_value
	beq     L0329
;
; kill();
;
	jsr     _kill
;
; audio_sfx(SFX_PICK);
;
	lda     #$08
	jsr     _audio_sfx
;
; continue;
;
	jmp     L0261
;
; local_temp1 = false; // to check if object is destroyed
;
L0329:	sta     _local_temp1
;
; ObjPropGetByIndex(lookup_index, PROP_SINK, array_value);
;
	lda     _lookup_index
	clc
	adc     #$04
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if ((local_flags & INTERACT_NON_SINK) && array_value)
;
	lda     _local_flags
	and     #$20
	beq     L032D
	lda     _array_value
	bne     L0334
;
; ObjPropGetByIndex(lookup_index, PROP_SINK, array_value);
;
L032D:	lda     _lookup_index
	clc
	adc     #$04
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if ((local_flags & INTERACT_SINK) && array_value == false)
;
	lda     _local_flags
	and     #$02
	beq     L0331
	lda     _array_value
	beq     L0334
;
; ObjPropGetByIndex(lookup_index, PROP_IRON, array_value);
;
L0331:	lda     _lookup_index
	clc
	adc     #$0D
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if ((local_flags & INTERACT_ACID) && array_value)
;
	lda     _local_flags
	and     #$80
	beq     L0335
	lda     _array_value
	beq     L0335
;
; local_temp1 = true;
;
L0334:	lda     #$01
	sta     _local_temp1
;
; if (local_temp1 != false)
;
L0335:	lda     _local_temp1
	beq     L0337
;
; kill();
;
	jsr     _kill
;
; audio_sfx(SFX_SINK);
;
	lda     #$07
	jsr     _audio_sfx
;
; continue;
;
	jmp     L0261
;
; local_temp1 = false;
;
L0337:	sta     _local_temp1
;
; ObjPropGetByIndex(lookup_index, PROP_SHUT, array_value);
;
	lda     _lookup_index
	clc
	adc     #$06
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if ((local_flags & INTERACT_OPEN) && array_value)
;
	lda     _local_flags
	and     #$08
	beq     L033B
	lda     _array_value
	bne     L033E
;
; ObjPropGetByIndex(lookup_index, PROP_OPEN, array_value);
;
L033B:	lda     _lookup_index
	clc
	adc     #$05
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if ((local_flags & INTERACT_SHUT) && array_value)
;
	lda     _local_flags
	and     #$10
	beq     L033F
	lda     _array_value
	beq     L033F
;
; local_temp1 = true;
;
L033E:	lda     #$01
	sta     _local_temp1
;
; if (local_temp1 != false)
;
L033F:	lda     _local_temp1
	beq     L0340
;
; kill();
;
	jsr     _kill
;
; audio_sfx(SFX_OPEN);
;
	lda     #$0C
	jsr     _audio_sfx
;
; continue;
;
	jmp     L0261
;
; ObjPropGetByIndex(lookup_index, PROP_YOU, array_value);
;
L0340:	lda     _lookup_index
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if ( (local_flags & INTERACT_KILL) && array_value )
;
	lda     _local_flags
	ldx     #$00
	and     #$04
	beq     L0344
	lda     _array_value
	beq     L0344
;
; kill();
;
	jsr     _kill
;
; for (local_index = 0; local_index < last_obj_index; ++local_index)
;
L0261:	ldx     #$00
L0344:	inc     _local_index
	jmp     L0323
;
; if (rule_exists[PROP_TELE])
;
L0260:	lda     _rule_exists+11
;
; process_teleports();
;
	jne     _process_teleports
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ create_object (unsigned char)
; ---------------------------------------------------------------

.segment	"BANKCODE"

.proc	_create_object: near

.segment	"BANKCODE"

;
; {
;
	jsr     pusha
;
; for (local_text_type = 0; local_text_type < MAX_OBJECTS; ++local_text_type)
;
	lda     #$00
	sta     _local_text_type
L0345:	lda     _local_text_type
	cmp     #$8C
	bcc     L034A
;
; }
;
	jmp     incsp1
;
; if (IS_KILLED(local_text_type)==false)
;
L034A:	ldy     _local_text_type
	lda     _objects+560,y
	and     #$08
;
; continue;
;
	jeq     L0349
;
; objects.type[local_text_type] = type;
;
	ldy     #$00
	lda     (sp),y
	ldy     _local_text_type
	sta     _objects+280,y
;
; if (type == TYPE_TEXT)
;
	ldy     #$00
	lda     (sp),y
	cmp     #$0F
	bne     L0347
;
; if (local_text_type >= last_text_index)
;
	lda     _local_text_type
	cmp     _last_text_index
	bcc     L0346
;
; last_text_index = local_text_type + 1;
;
	clc
	adc     #$01
	sta     _last_text_index
;
; if (last_text_index > last_obj_index)
;
L0346:	lda     _last_text_index
	sec
	sbc     _last_obj_index
	bcc     L0347
	beq     L0347
;
; last_obj_index = last_text_index;
;
	lda     _last_text_index
	sta     _last_obj_index
;
; ObjPropGet(type, PROP_PICK, array_value);
;
L0347:	lda     (sp),y
	tay
	lda     _obj_prop_lookup,y
	sta     _array_index
	lda     #$07
	clc
	adc     _array_index
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if (array_value)
;
	lda     _array_value
	beq     L004D
;
; ++helpers.pick_exists_as_object;
;
	inc     _helpers
;
; objects.text_type[local_text_type] = local_type;
;
L004D:	ldy     _local_text_type
	lda     _local_type
	sta     _objects+420,y
;
; objects.x[local_text_type] = local_temp1;
;
	ldy     _local_text_type
	lda     _local_temp1
	sta     _objects,y
;
; objects.y[local_text_type] = local_temp2;
;
	ldy     _local_text_type
	lda     _local_temp2
	sta     _objects+140,y
;
; array_value = create_direction | DIR_CREATED;
;
	lda     _create_direction
	ora     #$20
	sta     _array_value
;
; objects.direction[local_text_type] = array_value;
;
	ldy     _local_text_type
	lda     _array_value
	sta     _objects+560,y
;
; if (local_text_type >= last_obj_index)
;
	lda     _local_text_type
	cmp     _last_obj_index
	bcc     L0348
;
; last_obj_index = local_text_type + 1;
;
	clc
	adc     #$01
	sta     _last_obj_index
;
; helpers.rules_may_have_changed = true;
;
L0348:	lda     #$01
	sta     _helpers+4
;
; return;
;
	jmp     incsp1
;
; for (local_text_type = 0; local_text_type < MAX_OBJECTS; ++local_text_type)
;
L0349:	inc     _local_text_type
	jmp     L0345

.endproc

; ---------------------------------------------------------------
; void __near__ teleport (void)
; ---------------------------------------------------------------

.segment	"BANKCODE"

.proc	_teleport: near

.segment	"BANKCODE"

;
; for (local_temp1 = 0; local_temp1 < last_obj_index; ++local_temp1)
;
	lda     #$00
	sta     _local_temp1
	tax
L0351:	lda     _local_temp1
	cmp     _last_obj_index
	txa
	sbc     #$00
	bcc     L035D
;
; }
;
	rts
;
; map_index = objects.type[local_temp1]; // temporary move to map_index to optimize ObjPropGet
;
L035D:	ldy     _local_temp1
	lda     _objects+280,y
	sta     _map_index
;
; ObjPropGet(map_index, PROP_TELE, array_value);
;
	ldy     _map_index
	lda     _obj_prop_lookup,y
	sta     _array_index
	lda     #$0B
	clc
	adc     _array_index
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if (array_value==false || IS_KILLED(local_temp1))
;
	lda     _array_value
	jeq     L035C
	ldy     _local_temp1
	lda     _objects+560,y
	and     #$08
	jne     L035C
;
; local_text_type = local_temp1;
;
	lda     _local_temp1
	sta     _local_text_type
;
; if (objects.x[local_temp1] == local_x && objects.y[local_temp1] == local_y)
;
	ldy     _local_temp1
	lda     _objects,y
	cmp     _local_x
	jne     L035C
	ldy     _local_temp1
	lda     _objects+140,y
	cmp     _local_y
	jne     L035C
;
; ++local_temp1;
;
L0356:	inc     _local_temp1
;
; if (local_temp1 == last_obj_index)
;
	lda     _last_obj_index
	cmp     _local_temp1
	bne     L0096
;
; local_temp1 = 0;
;
	lda     #$00
	sta     _local_temp1
;
; map_index = objects.type[local_temp1]; // temporary move to map_index to optimize ObjPropGet
;
L0096:	ldy     _local_temp1
	lda     _objects+280,y
	sta     _map_index
;
; ObjPropGet(map_index, PROP_TELE, array_value);
;
	ldy     _map_index
	lda     _obj_prop_lookup,y
	sta     _array_index
	lda     #$0B
	clc
	adc     _array_index
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if (array_value == false || IS_KILLED(local_temp1))
;
	lda     _array_value
	beq     L035B
	ldy     _local_temp1
	lda     _objects+560,y
	and     #$08
	bne     L035B
;
; if (objects.x[local_temp1] == local_x && objects.y[local_temp1] == local_y)
;
	ldy     _local_temp1
	lda     _objects,y
	cmp     _local_x
	bne     L00B0
	ldy     _local_temp1
	lda     _objects+140,y
	cmp     _local_y
	beq     L035B
;
; array_value = objects.x[local_temp1];
;
L00B0:	ldy     _local_temp1
	lda     _objects,y
	sta     _array_value
;
; objects.x[local_index] = array_value;
;
	ldy     _local_index
	lda     _array_value
	sta     _objects,y
;
; array_value = objects.y[local_temp1];
;
	ldy     _local_temp1
	lda     _objects+140,y
	sta     _array_value
;
; objects.y[local_index] = array_value;
;
	ldy     _local_index
	lda     _array_value
	sta     _objects+140,y
;
; if (local_type == TYPE_TEXT || obj_is_word[local_type])
;
	lda     _local_type
	cmp     #$0F
	beq     L035A
	ldy     _local_type
	lda     _obj_is_word,y
	beq     L00C8
;
; helpers.rules_may_have_changed = true;
;
L035A:	lda     #$01
	sta     _helpers+4
;
; audio_sfx(SFX_TELE);
;
L00C8:	lda     #$09
	jmp     _audio_sfx
;
; } while (local_temp1 != local_text_type);
;
L035B:	lda     _local_text_type
	cmp     _local_temp1
	jne     L0356
;
; for (local_temp1 = 0; local_temp1 < last_obj_index; ++local_temp1)
;
	ldx     #$00
L035C:	inc     _local_temp1
	jmp     L0351

.endproc

; ---------------------------------------------------------------
; void __near__ create_bang (void)
; ---------------------------------------------------------------

.segment	"BANKCODE"

.proc	_create_bang: near

.segment	"BANKCODE"

;
; MapGet(local_temp1, local_temp2, array_value);
;
	ldy     _local_temp2
	lda     _map_lookup,y
	clc
	adc     _local_temp1
	sta     _array_index
	ldy     _array_index
	lda     _map,y
	sta     _array_value
;
; if (array_value & INTERACT_STOP)
;
	and     #$40
;
; return;
;
	bne     L00D2
;
; create_object(TYPE_BANG);
;
	lda     #$0B
	jmp     _create_object
;
; }
;
L00D2:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ kill (void)
; ---------------------------------------------------------------

.segment	"BANKCODE"

.proc	_kill: near

.segment	"BANKDATA"

L00E2:
	.res	1,$00

.segment	"BANKCODE"

;
; create_direction = objects.direction[local_index];
;
	ldy     _local_index
	lda     _objects+560,y
	sta     _create_direction
;
; objects.direction[local_index] = DIR_KILLED;
;
	ldy     _local_index
	lda     #$08
	sta     _objects+560,y
;
; if (local_type == TYPE_TEXT || obj_is_word[local_type])
;
	lda     _local_type
	cmp     #$0F
	beq     L0363
	ldy     _local_type
	lda     _obj_is_word,y
	beq     L0364
;
; helpers.rules_may_have_changed = true;
;
L0363:	lda     #$01
	sta     _helpers+4
;
; ObjPropGetByIndex(lookup_index, PROP_PICK, array_value);
;
L0364:	lda     _lookup_index
	clc
	adc     #$07
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if (array_value)
;
	lda     _array_value
	beq     L0366
;
; --helpers.pick_exists_as_object;
;
	dec     _helpers
;
; for (has_type = 0; has_type < TYPE_MAX; ++has_type)
;
	lda     #$00
L0366:	sta     L00E2
L0367:	lda     L00E2
	cmp     #$10
	bcs     L0368
;
; if (obj_has[local_type] & (one_lshift_lookup[has_type]))
;
	ldx     #$00
	lda     _local_type
	asl     a
	bcc     L0361
	inx
	clc
L0361:	adc     #<(_obj_has)
	sta     ptr1
	txa
	adc     #>(_obj_has)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     pushax
	ldx     #$00
	lda     L00E2
	asl     a
	bcc     L0362
	inx
	clc
L0362:	adc     #<(_one_lshift_lookup)
	sta     ptr1
	txa
	adc     #>(_one_lshift_lookup)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     tosandax
	stx     tmp1
	ora     tmp1
	beq     L0100
;
; local_temp1 = local_x;
;
	lda     _local_x
	sta     _local_temp1
;
; local_temp2 = local_y;
;
	lda     _local_y
	sta     _local_temp2
;
; create_object(has_type);
;
	lda     L00E2
	jsr     _create_object
;
; helpers.something_transformed = true;
;
	lda     #$01
	sta     _helpers+7
;
; for (has_type = 0; has_type < TYPE_MAX; ++has_type)
;
L0100:	inc     L00E2
	jmp     L0367
;
; ObjPropGetByIndex(lookup_index, PROP_BOOM, array_value);
;
L0368:	lda     _lookup_index
	clc
	adc     #$0A
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if (array_value)
;
	lda     _array_value
	beq     L0136
;
; helpers.something_exploded = true;
;
	lda     #$01
	sta     _helpers+6
;
; local_temp1 = local_x;
;
	lda     _local_x
	sta     _local_temp1
;
; if (local_y > 0)
;
	lda     _local_y
	beq     L0369
;
; local_temp2 = local_y - 1;
;
	sec
	sbc     #$01
	sta     _local_temp2
;
; create_bang();
;
	jsr     _create_bang
;
; if (local_y < MAP_SIZE_Y - 1)
;
L0369:	lda     _local_y
	cmp     #$0B
	bcs     L036A
;
; local_temp2 = local_y + 1;
;
	clc
	adc     #$01
	sta     _local_temp2
;
; create_bang();
;
	jsr     _create_bang
;
; local_temp2 = local_y;
;
L036A:	lda     _local_y
	sta     _local_temp2
;
; if (local_x < MAP_SIZE_X - 1)
;
	lda     _local_x
	cmp     #$13
	bcs     L036B
;
; local_temp1 = local_x + 1;
;
	clc
	adc     #$01
	sta     _local_temp1
;
; create_bang();
;
	jsr     _create_bang
;
; if (local_x > 0)
;
L036B:	lda     _local_x
	beq     L0136
;
; local_temp1 = local_x - 1;
;
	sec
	sbc     #$01
	sta     _local_temp1
;
; create_bang();
;
	jmp     _create_bang
;
; }
;
L0136:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ process_teleports (void)
; ---------------------------------------------------------------

.segment	"BANKCODE"

.proc	_process_teleports: near

.segment	"BANKCODE"

;
; memset(map, INTERACT_NONE, sizeof(map));
;
	ldy     #$00
	tya
L0142:	sta     _map,y
	iny
	cpy     #$F0
	bne     L0142
;
; for (local_index = 0; local_index < last_obj_index; ++local_index)
;
	lda     #$00
	sta     _local_index
	tax
L036E:	lda     _local_index
	cmp     _last_obj_index
	txa
	sbc     #$00
	bcs     L0370
;
; local_type = objects.type[local_index];
;
	ldy     _local_index
	lda     _objects+280,y
	sta     _local_type
;
; ObjPropGet(local_type, PROP_TELE, array_value);
;
	ldy     _local_type
	lda     _obj_prop_lookup,y
	sta     _array_index
	lda     #$0B
	clc
	adc     _array_index
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if (array_value == false)
;
	lda     _array_value
;
; continue;
;
	beq     L036F
;
; if (IS_CREATED(local_index))
;
	ldy     _local_index
	lda     _objects+560,y
	and     #$20
;
; continue;
;
	bne     L036F
;
; if (IS_KILLED(local_index))
;
	ldy     _local_index
	lda     _objects+560,y
	and     #$08
;
; continue;
;
	bne     L036F
;
; local_x = objects.x[local_index];
;
	ldy     _local_index
	lda     _objects,y
	sta     _local_x
;
; local_y = objects.y[local_index];
;
	ldy     _local_index
	lda     _objects+140,y
	sta     _local_y
;
; MapSet(local_x, local_y, PREPROCESS_TELE);
;
	ldy     _local_y
	lda     _map_lookup,y
	clc
	adc     _local_x
	sta     _array_index
	lda     #$01
	sta     _array_value
	ldy     _array_index
	lda     _array_value
	sta     _map,y
;
; for (local_index = 0; local_index < last_obj_index; ++local_index)
;
L036F:	inc     _local_index
	jmp     L036E
;
; for (local_index = 0; local_index < last_obj_index; ++local_index)
;
L0370:	lda     #$00
	sta     _local_index
L0371:	lda     _local_index
	cmp     _last_obj_index
	txa
	sbc     #$00
	bcs     L017D
;
; if (IS_KILLED(local_index))
;
	ldy     _local_index
	lda     _objects+560,y
	and     #$08
;
; continue;
;
	bne     L0375
;
; if (IS_CREATED(local_index))
;
	ldy     _local_index
	lda     _objects+560,y
	and     #$20
;
; continue;
;
	bne     L0375
;
; local_type = objects.type[local_index];
;
	ldy     _local_index
	lda     _objects+280,y
	sta     _local_type
;
; local_x = objects.x[local_index];
;
	ldy     _local_index
	lda     _objects,y
	sta     _local_x
;
; local_y = objects.y[local_index];
;
	ldy     _local_index
	lda     _objects+140,y
	sta     _local_y
;
; MapGet(local_x, local_y, local_flags);
;
	ldy     _local_y
	lda     _map_lookup,y
	clc
	adc     _local_x
	sta     _array_index
	ldy     _array_index
	lda     _map,y
	sta     _local_flags
;
; ObjPropGet(local_type, PROP_TELE, array_value);
;
	ldy     _local_type
	lda     _obj_prop_lookup,y
	sta     _array_index
	lda     #$0B
	clc
	adc     _array_index
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if ((local_flags & PREPROCESS_TELE) && array_value == false)
;
	lda     _local_flags
	and     #$01
	beq     L0375
	lda     _array_value
	bne     L0375
;
; teleport();
;
	jsr     _teleport
;
; for (local_index = 0; local_index < last_obj_index; ++local_index)
;
	ldx     #$00
L0375:	inc     _local_index
	jmp     L0371
;
; }
;
L017D:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ preprocess_interactions (void)
; ---------------------------------------------------------------

.segment	"BANKCODE"

.proc	_preprocess_interactions: near

.segment	"BANKCODE"

;
; helpers.pick_exists_as_object = 0;
;
	lda     #$00
	sta     _helpers
;
; memset(map, INTERACT_NONE, sizeof(map));
;
	tay
L01BE:	sta     _map,y
	iny
	cpy     #$F0
	bne     L01BE
;
; for (local_index = 0; local_index < last_obj_index; ++local_index)
;
	lda     #$00
	sta     _local_index
	tax
L0378:	lda     _local_index
	cmp     _last_obj_index
	txa
	sbc     #$00
	bcc     L0381
;
; }
;
	rts
;
; if (IS_KILLED(local_index))
;
L0381:	ldy     _local_index
	lda     _objects+560,y
	and     #$08
;
; continue;
;
	jne     L0380
;
; objects.direction[local_index] &= ( (~DIR_CREATED) & (~DIR_CHANGED));
;
	lda     #<(_objects+560)
	ldx     #>(_objects+560)
	clc
	adc     _local_index
	bcc     L01CE
	inx
L01CE:	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	and     #$CF
	sta     (ptr1),y
;
; local_type = objects.type[local_index];
;
	ldy     _local_index
	lda     _objects+280,y
	sta     _local_type
;
; local_temp1 = INTERACT_NONE; // interaction flags
;
	lda     #$00
	sta     _local_temp1
;
; local_x = objects.x[local_index];
;
	ldy     _local_index
	lda     _objects,y
	sta     _local_x
;
; local_y = objects.y[local_index];
;
	ldy     _local_index
	lda     _objects+140,y
	sta     _local_y
;
; map_index = MapGetIndex(local_x, local_y);
;
	ldy     _local_y
	lda     _map_lookup,y
	clc
	adc     _local_x
	sta     _map_index
;
; local_flags = map[map_index];
;
	ldy     _map_index
	lda     _map,y
	sta     _local_flags
;
; lookup_index = obj_prop_lookup[local_type];
;
	ldy     _local_type
	lda     _obj_prop_lookup,y
	sta     _lookup_index
;
; ObjPropGetByIndex(lookup_index, PROP_YOU, array_value);
;
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if (array_value)
;
	lda     _array_value
	beq     L0379
;
; local_flags |= INTERACT_YOU;
;
	lda     _local_flags
	ora     #$01
	sta     _local_flags
;
; ObjPropGetByIndex(lookup_index, PROP_KILL, array_value);
;
L0379:	lda     _lookup_index
	clc
	adc     #$08
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if (array_value)
;
	lda     _array_value
	beq     L037A
;
; local_flags |= INTERACT_KILL;
;
	lda     _local_flags
	ora     #$04
	sta     _local_flags
;
; ObjPropGetByIndex(lookup_index, PROP_SHUT, array_value);
;
L037A:	lda     _lookup_index
	clc
	adc     #$06
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if (array_value)
;
	lda     _array_value
	beq     L037B
;
; local_flags |= INTERACT_SHUT;
;
	lda     _local_flags
	ora     #$10
	sta     _local_flags
;
; ObjPropGetByIndex(lookup_index, PROP_OPEN, array_value);
;
L037B:	lda     _lookup_index
	clc
	adc     #$05
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if (array_value)
;
	lda     _array_value
	beq     L037C
;
; local_flags |= INTERACT_OPEN;
;
	lda     _local_flags
	ora     #$08
	sta     _local_flags
;
; ObjPropGetByIndex(lookup_index, PROP_SINK, array_value);
;
L037C:	lda     _lookup_index
	clc
	adc     #$04
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if (array_value)
;
	lda     _array_value
	beq     L037D
;
; local_flags |= INTERACT_SINK;
;
	lda     _local_flags
	ora     #$02
;
; else
;
	jmp     L0377
;
; local_flags |= INTERACT_NON_SINK;
;
L037D:	lda     _local_flags
	ora     #$20
L0377:	sta     _local_flags
;
; ObjPropGetByIndex(lookup_index, PROP_STOP, array_value);
;
	lda     _lookup_index
	clc
	adc     #$02
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if (array_value)
;
	lda     _array_value
	beq     L037E
;
; local_flags |= INTERACT_STOP;
;
	lda     _local_flags
	ora     #$40
	sta     _local_flags
;
; ObjPropGetByIndex(lookup_index, PROP_ACID, array_value);
;
L037E:	lda     _lookup_index
	clc
	adc     #$0C
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if (array_value)
;
	lda     _array_value
	beq     L037F
;
; local_flags |= INTERACT_ACID;
;
	lda     _local_flags
	ora     #$80
	sta     _local_flags
;
; ObjPropGetByIndex(lookup_index, PROP_PICK, array_value);
;
L037F:	lda     _lookup_index
	clc
	adc     #$07
	sta     _array_index
	ldy     _array_index
	lda     _obj_prop,y
	sta     _array_value
;
; if (array_value)
;
	lda     _array_value
	beq     L0256
;
; ++helpers.pick_exists_as_object;
;
	inc     _helpers
;
; map[map_index] = local_flags;
;
L0256:	ldy     _map_index
	lda     _local_flags
	sta     _map,y
;
; for (local_index = 0; local_index < last_obj_index; ++local_index)
;
	ldx     #$00
L0380:	inc     _local_index
	jmp     L0378

.endproc

