;
; File generated by cc65 v 2.18 - Git f75657d
;
	.fopt		compiler,"cc65 v 2.18 - Git f75657d"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_move_direction_lookup_x
	.export		_move_direction_lookup_y
	.export		_map_lookup
	.export		_obj_prop_lookup
	.export		_one_lshift_lookup
	.export		_reverted_direction_lookup

.segment	"BANKDATA"

_map_lookup:
	.byte	$00
	.byte	$14
	.byte	$28
	.byte	$3C
	.byte	$50
	.byte	$64
	.byte	$78
	.byte	$8C
	.byte	$A0
	.byte	$B4
	.byte	$C8
	.byte	$DC
_obj_prop_lookup:
	.byte	$00
	.byte	$10
	.byte	$20
	.byte	$30
	.byte	$40
	.byte	$50
	.byte	$60
	.byte	$70
	.byte	$80
	.byte	$90
	.byte	$A0
	.byte	$B0
	.byte	$C0
	.byte	$D0
	.byte	$E0
	.byte	$F0
_move_direction_lookup_x:
	.byte	$00
	.byte	$FF
	.byte	$00
	.byte	$01
	.byte	$00
_move_direction_lookup_y:
	.byte	$01
	.byte	$00
	.byte	$FF
	.byte	$00
	.byte	$00
_reverted_direction_lookup:
	.byte	$02
	.byte	$03
	.byte	$00
	.byte	$01
	.byte	$04
_one_lshift_lookup:
	.word	$0001
	.word	$0002
	.word	$0004
	.word	$0008
	.word	$0010
	.word	$0020
	.word	$0040
	.word	$0080
	.word	$0100
	.word	$0200
	.word	$0400
	.word	$0800
	.word	$1000
	.word	$2000
	.word	$4000
	.word	$8000

